[fs]

fs_read_bucket="sgmw-test-team"
fs_upload_api = "http://10.10.3.14:20025/api/document/uploadFile"
fs_client_api = "http://10.10.3.14:20025/api/document/client/uploadFile"
default_space_id = 29

[mysql]

host = "10.10.3.14"
port = "3306"
user = "root"
password = "Orienlink123@"

[gofast]

host= "http://10.10.3.13:18082"